name: dealers_app
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.1.0+13

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  fluttertoast: ^7.1.1
  http: ^0.12.2
  device_info: ^0.4.2+8
  intl: ^0.16.1
  url_launcher: ^5.7.4


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0
  shared_preferences: ^0.5.12+4
  carousel_pro: ^1.0.0
  flutter_slidable: ^0.6.0
  get_it: ^7.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.9.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/icon.jpg"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/ffc.png
    - assets/images/1.png
    - assets/images/2.jpg
    - assets/images/3.jpg
    - assets/images/4.jpg
    - assets/images/5.jpg
    - assets/images/6.png
    - assets/images/sona.png
    - assets/images/sonaurea.png
    - assets/images/ffcdap.png
    - assets/images/ffcsop.png
    - assets/images/ffcmop.png
    - assets/images/sonaboron.png
    - assets/images/sonazinc.png
    - assets/images/wheat.png
    - assets/images/cotton.png
    - assets/images/rice.png
    - assets/images/date.png
    - assets/images/banana.png
    - assets/images/maize.png
    - assets/images/mango.png
    - assets/images/sunflower.png
    - assets/images/guava.png
    - assets/images/sugarcane.png
    - assets/images/orange.png
    - assets/images/salt.png
    - assets/images/potato.png
    - assets/images/vegetables.png
    - assets/images/garden.png
    - assets/images/salt.png
    - assets/images/fertility.png
    - assets/images/sonadap.png
    - assets/images/sonaureag.png
    - assets/icon.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Urdu
      fonts:
        - asset: assets/fonts/Jameel-Noori-Nastaleeq.ttf
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
